name: Publish image

on:
  pull_request

jobs:
  publish:
    env:
      IMAGE_NAME: "dhis2/locustio:latest"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create image
      env:
        GITHUB_USERNAME: x-access-token
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker build -t $IMAGE_NAME ./docker

    - name: Test image
      run: |
        docker run --publish 8089:8089 --detach --name locust $IMAGE_NAME
        bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8089)" != "200" ]]; do sleep 5; done'


