name: Publish image

on:
  push:
    paths:
      - 'docker/*'

jobs:
  publish:
    env:
      IMAGE_NAME: "dhis2/locustio:latest"
      DOCKER_BUILDKIT: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create image
      run: |
        docker pull $IMAGE_NAME
        docker build --cache-from $IMAGE_NAME -t $IMAGE_NAME --build-arg BUILDKIT_INLINE_CACHE=1 ./docker

    - name: Test image
      timeout-minutes: 3
      run: |
        docker-compose up -d
        bash -c 'while [[ "$(curl -o /dev/null -w ''%{http_code}'' localhost:8089)" != "200" ]]; do sleep 5; done'

    - name: Publish image
      run: |
        echo ${{ secrets.DHIS2_BOT_DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DHIS2_BOT_DOCKER_HUB_USERNAME }} --password-stdin
        docker push $IMAGE_NAME



